### ISSUE TITLE
"undefined" section is generated

### ISSUE THREAD

**Issue by nju-ics** [ymcatar/gitbook-plugin-sectionx#1]
Hi, I use this plugin with the following code:
```
<!--sec title="Intrudoection" id="section0" show=true ces-->

aaaaa

<!--endsec-->
```
But it generates an "undefined" section output. See the top section [here](http://nju-ics.gitbooks.io/ics2015-programming-assignment/content/why.html). 

Here is my book.json:
```
{
	"gitbook": "2.1.0",
    "plugins": [
        "tkcolors",
		"betterchinese",
		"yahei",
		"sectionx"
    ],
    "pluginsConfig": {}
}
```

When building the book, it gives the following warning message:
```
warn: Hook 'page 'used by plugin 'gitbook-plugin-sectionx' has been removed or is deprecated 
```
I am not sure whether this warning message has something to do with the "undefined" section.

I don't know how to solve this problem. Would you please tell me how to handle it? Thanks.

**Comment by ymcatar** [comment]
I think I had updated the syntax but forgot to update the README, by following the old documentation you are using the old syntax, so it didn't work.

Just add ```data-``` in front of every parameters and it should work.

```
<!--sec data-title="Intrudoection" data-id="section0" data-show=true ces-->

aaaaa

<!--endsec-->
```

I am sorry for that. Hope that you can get it working.

btw: you can see the markdown for the [example page](http://ymcatar.gitbooks.io/gitbook-test/content/testing_sectionx.html) right [here](https://raw.githubusercontent.com/ymcatar/gitbook-test/master/testing_sectionx.md) for reference.

**Comment by ymcatar** [comment]
The error message ```warn: Hook 'page 'used by plugin 'gitbook-plugin-sectionx' has been removed or is deprecated ``` can be safely ignored. The 'page' hooks (very useful in this plugin) has been deprecated in GitBook, but it is very likely to not be removed.

**Comment by nju-ics** [comment]
Now it works! This plugin is very useful for me. Thanks a lot!
