### ISSUE TITLE
An ability to create switch button between several programming languages

### ISSUE THREAD

**Issue by mathbunnyru** [ymcatar/gitbook-plugin-sectionx#10]
I write a project with api for several programming languages. I want to add an ability to add switch key to switch between for example C++ and Python. For each language I want the syntax highlighting. Please, let me know, is it possible or not?

**Comment by ymcatar** [comment]
I think you can add two buttons, each responsible for toggling two section with `data-show` set to `false`. It might be a lot of work though but it is possible.

**Comment by mathbunnyru** [comment]
@ymcatar I found plugin-codetabs, which is better for my purposes. Thank you!

**Comment by ymcatar** [comment]
Good to hear.
