### ISSUE TITLE
set the panel is collapsed

### ISSUE THREAD

**Issue by smallknife1120** [ymcatar/gitbook-plugin-sectionx#3]
it's look like the image
![11](https://cloud.githubusercontent.com/assets/4242148/15284801/2f300c4c-1b86-11e6-9f8f-49d982d079f2.png)

can you? 
thanks

**Comment by ymcatar** [comment]
Sorry, didn't quite understand your request. Can you explain more?

**Comment by voxelbusters** [comment]
He meant is it possible to have a section collapsed by default?

**Comment by ymcatar** [comment]
Try this:

```
<!--sec data-title="Introduction" data-id="section0" data-show=false ces-->

Insert markdown content here (you should start with h3 if you use heading).

<!--endsec-->
```

`data-show` should let you toggle that behavior.

**Comment by voxelbusters** [comment]
But this seems to make the section completely invisible. Right?

**Comment by ymcatar** [comment]
Oh, I see. I will add this.

**Comment by voxelbusters** [comment]
Cool thanks!

**Comment by ymcatar** [comment]
Sorry for the long wait. I will publish the update by tomorrow.

**Comment by ymcatar** [comment]
It is available now. Please check it out.
